// File generated by running `flutterfire configure`
// (or in our case, manually copying the config!)

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// A simple class to hold our Firebase configuration.
/// The `flutterfire` tool would generate this automatically.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // This is a simple setup. For your project (running on web/chrome),
    // we will just return the 'web' configuration.
    if (kIsWeb) {
      return web;
    }

    // You can add configurations for Android and iOS here later if you
    // decide to build for mobile, but for now, 'web' is all we need.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return web; // Using web config as a default for mobile
      case TargetPlatform.iOS:
        return web; // Using web config as a default for mobile
      default:
        // Default to web for other platforms (like desktop)
        return web;
    }
  }

  // --- THIS IS YOUR NEW INTEGRATED CONFIG ---
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBTssiAfkegxTTuJ5A-FkTFgPLNjIB3su0",
    authDomain: "home-power-monitor-752b7.firebaseapp.com",
    databaseURL: "https://home-power-monitor-752b7-default-rtdb.firebaseio.com",
    projectId: "home-power-monitor-752b7",
    storageBucket: "home-power-monitor-752b7.firebasestorage.app",
    messagingSenderId: "53707925817",
    appId: "1:53707925817:web:0755040d5449bbbccb20e8",
    measurementId: "G-Y0Q7Q9YMBN",
  );
  // --- END YOUR CONFIG ---
}