[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM6

build_flags = -DCORE_DEBUG_LEVEL=1

lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4
  tzapu/WiFiManager @ ^2.0.17

lib_ldf_mode = deep+
